# Generated by Django 6.0.3 on 2026-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='mobile_number',
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
    ]
