# Generated by Django 6.0.3 on 2026-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0002_login_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
